name: Android CI

env:
  NDK_VERSION: "28.2.13676358"

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**.md", "LICENSE", ".gitignore", ".github/ISSUE_TEMPLATE/**", "art/**", "fastlane/**", "script/**" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**.md", "LICENSE", ".gitignore", ".github/ISSUE_TEMPLATE/**", "art/**", "fastlane/**", "script/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Export ANDROID_HOME to env
        run: echo "ANDROID_HOME=$ANDROID_HOME" >> "$GITHUB_ENV"

      - name: Cache NDK
        id: cache-ndk
        uses: actions/cache@v5.0.3
        with:
          path: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
          key: ${{ runner.os }}-ndk-${{ env.NDK_VERSION }}

      - name: Install NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Write sign info
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.repository == 'Super12138/VerveDo'
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo releaseStoreFile='${{ github.workspace }}/key.jks' >> gradle.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Fix Permissions for Debug Keystore Path
        if: github.ref != 'refs/heads/main'
        run: sudo chmod -R 777 /home/runner/.config/.android

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        if: success() && github.event_name != 'pull_request' && github.repository == 'Super12138/VerveDo'
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Release
          path: ${{ github.workspace }}/app/build/outputs/apk/release
